/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto4;

import CG.Matriz3;
import CG.Punto3;
import CG.Transform.Rotate;
import CG.Transform.Scale;
import CG.Transform.Translate;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 */
public class PnlTransform extends javax.swing.JPanel {

    private Main principal;
    /**
     * Creates new form PnlTransform
     */
    public PnlTransform(Main principal) {
        initComponents();
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPosX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPosY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPosZ = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFOV = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPosX1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPosY1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPosZ1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPosX2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPosY2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPosZ2 = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Position"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jPanel1.add(jLabel1);

        txtPosX.setText("40");
        jPanel1.add(txtPosX);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("y");
        jPanel1.add(jLabel2);

        txtPosY.setText("40");
        jPanel1.add(txtPosY);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("z");
        jPanel1.add(jLabel3);

        txtPosZ.setText("20");
        jPanel1.add(txtPosZ);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("d (FOV)");

        txtFOV.setText("25");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFOV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFOV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotation"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        jPanel3.add(jLabel4);

        txtPosX1.setText("0");
        jPanel3.add(txtPosX1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("y");
        jPanel3.add(jLabel5);

        txtPosY1.setText("0");
        jPanel3.add(txtPosY1);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("z");
        jPanel3.add(jLabel6);

        txtPosZ1.setText("0");
        jPanel3.add(txtPosZ1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Scale"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("x");
        jPanel4.add(jLabel7);

        txtPosX2.setText("1");
        jPanel4.add(txtPosX2);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("y");
        jPanel4.add(jLabel8);

        txtPosY2.setText("1");
        jPanel4.add(txtPosY2);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("z");
        jPanel4.add(jLabel9);

        txtPosZ2.setText("1");
        jPanel4.add(txtPosZ2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    public String getPositionX() {
        return txtPosX.getText();
    }
    
    public String getPositionY() {
        return txtPosY.getText();
    }
    
    public String getPositionZ() {
        return txtPosZ.getText();
    }
    
    public String getRotationX() {
        return txtPosX1.getText();
    }
    
    public String getRotationY() {
        return txtPosY1.getText();
    }
    
    public String getRotationZ() {
        return txtPosZ1.getText();
    }
    
    public String getScaleX() {
        return txtPosX2.getText();
    }
    
    public String getScaleY() {
        return txtPosY2.getText();
    }
    
    public String getScaleZ() {
        return txtPosZ2.getText();
    }
    
    public void update(){
        System.out.println("Holaaaa");
        
        double x = Double.parseDouble(getPositionX());
        double y = Double.parseDouble(getPositionY());
        double z = Double.parseDouble(getPositionZ());
        
        double tx = Double.parseDouble(getRotationX());
        double ty = Double.parseDouble(getRotationY());
        double tz = Double.parseDouble(getRotationZ());
        
        double sx = Double.parseDouble(getScaleX());
        double sy = Double.parseDouble(getScaleY());
        double sz = Double.parseDouble(getScaleZ());
        
        int pe = Integer.parseInt(txtFOV.getText());
        
        //for(int i = 0; i<8; i++) {
        //    vertices3D.set(i, Punto3.preTimes(vertices3D.get(i),
        //            Matriz3.transpose((new Translate(20.0, 20.0, 15.0)))));
        //}
        
        //from2Dto3D();
        
        //g2d.setColor(Color.orange);
        //paintAllEdges(g2d);
        
        Main main = Main.getInstance();
        
        for (int i = 0; i < 8; i++) {
            main.getPanelProjections().vertices3D.set(i, Punto3.preTimes(main.getPanelProjections().vertices3D.get(i),
                    Matriz3.transpose(new Translate(x,y,z))));
        }
        
        
        for (int i = 0; i < 8; i++) {
            main.getPanelProjections().vertices3D.set(i, Punto3.preTimes(main.getPanelProjections().vertices3D.get(i),
                    Matriz3.transpose(new Scale(sx,sy,sz))));
        }
        
        
        for (int i = 0; i < 8; i++) {
            main.getPanelProjections().vertices3D.set(i, Punto3.preTimes(main.getPanelProjections().vertices3D.get(i),
                    Matriz3.transpose(new Rotate(tx,ty,tz))));
        }
        
        main.getPanelProjections().from2Dto3D(pe);
        main.getPanelProjections().graphics2.setColor(Color.red);
        main.getPanelProjections().paintAllEdges(main.getPanelProjections().graphics2);
        main.getPanelProjections().Repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtFOV;
    private javax.swing.JTextField txtPosX;
    private javax.swing.JTextField txtPosX1;
    private javax.swing.JTextField txtPosX2;
    private javax.swing.JTextField txtPosY;
    private javax.swing.JTextField txtPosY1;
    private javax.swing.JTextField txtPosY2;
    private javax.swing.JTextField txtPosZ;
    private javax.swing.JTextField txtPosZ1;
    private javax.swing.JTextField txtPosZ2;
    // End of variables declaration//GEN-END:variables

}
